version: '3.8'

services:
  ids:
    build:
      context: ./ids
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info

  face-recognition:
    build:
      context: ./vision
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./models:/app/models
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - MODEL_PATH=/app/models

  monitoring:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: