trigger:
  - main
  - develop

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Security_Scan
  jobs:
  - job: SecurityChecks
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.9'
    
    - script: |
        pip install bandit safety
        bandit -r . -f json -o bandit-results.json
        safety check
      displayName: 'Security Scan'

- stage: Build
  jobs:
  - job: BuildAndTest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.9'
    
    - script: |
        pip install -r requirements.txt
        pytest tests/ --junitxml=test-results.xml
      displayName: 'Run Tests'
    
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'test-results.xml'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure subscription'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az webapp up --name $(webAppName) --resource-group $(resourceGroup)
