version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=cyberlab
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=cyberlab
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
