name: Security Pipeline

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install bandit safety
        
    - name: Run Bandit
      run: bandit -r . -f json -o bandit-results.json
      
    - name: Run Safety Check
      run: safety check
      
    - name: Run Tests
      run: |
        pip install pytest pytest-cov
        pytest tests/ --cov=./ --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

  docker-build:
    runs-on: ubuntu-latest
    needs: security-checks
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop')
    steps:
    - uses: actions/checkout@v5
    
    - name: Build and push Docker images
      run: |
        docker-compose build
        # Здесь можно добавить push в registry, если необходимо